### ISSUE TITLE
How to write text

### ISSUE THREAD

**Issue by LewisMcMahon** [TheAndyRoid/PythonPlugin#1]
Could you write and quick example of how to use this to show text?

Also where do you store the python libs? so tht i can link them as an external lib in my editor

**Comment by TheAndyRoid** [comment]
This plugin does not provide the means to write text by its self. You must use an external library, I've included an example "DateTime.py" that uses pycairo to write the current date and time to screen.
A simple installer for Pycairo is avalible here http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo

The python libs are compiled into the .dll . I've not created externally read-able python libs, the wiki and source code are currently all that is available.
